export const statusLabels: Record<string, string> = {
  pending: '검토 중',
  published: '공개',
  hidden: '숨김',
  rejected: '보완 요청',
  accepted: '반영 완료',
  cancelled: '취소',
  active: '활성',
  suspended: '이용 제한',
  deleted: '삭제',
  resolved: '처리 완료',
  dismissed: '기각',
  accepted_pending_release: '채택 · 반영 대기',
  revoked: '권한 회수',
};
export const eventLabels: Record<string, string> = {
  pageview: '페이지 열람',
  search: '검색',
  copy: '프롬프트 복사',
  vote: '대체 경험 표시',
  signup: '회원가입',
  post: '글 작성',
  share: '공유',
};
export const actionLabels: Record<string, string> = {
  login: '관리자 로그인',
  logout: '관리자 로그아웃',
  'admin-grant': '관리자 권한 부여',
  'admin-revoke': '관리자 권한 회수',
  'user-create': '회원 추가',
  'user-suspend': '회원 이용 제한',
  'user-restore': '회원 제한 해제',
  'user-sessions-revoke': '회원 전체 로그아웃',
  'service-save': 'SaaS 저장',
  'service-publish': 'SaaS 공개',
  'service-reject': 'SaaS 보완 요청',
  'service-hide': 'SaaS 공개 중지',
  'service-edit-accept': '수정 제안 반영',
  'service-edit-reject': '수정 제안 보완 요청',
  'posts-hide': '게시글 숨김',
  'posts-restore': '게시글 복구',
  'posts-pin': '게시글 고정',
  'posts-unpin': '게시글 고정 해제',
  'comments-hide': '댓글 숨김',
  'comments-restore': '댓글 복구',
  'reports-resolve': '신고 처리',
  'reports-dismiss': '신고 기각',
  'suggestions-accept': '의견 채택',
  'suggestions-reject': '의견 반려',
  'notice-create': '공지 작성',
  'setting-update': '운영 설정 변경',
};
